package entities;
// Generated 11/04/2020 11:08:44 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table(name = "evento", catalog = "localizapp")
public class Evento implements java.io.Serializable {

	private int idevento;
	private String nombre;
	private Date fechaInicio;
	private Date fechaFin;
	private String horaInicio;
	private String horaFin;
	private String descripcion;
	private Set<Poligono> poligonos = new HashSet<Poligono>(0);
	private Set<Punto> puntos = new HashSet<Punto>(0);

	public Evento() {
	}

	public Evento(int idevento, String nombre, Date fechaInicio, Date fechaFin, String horaInicio, String horaFin,
			String descripcion) {
		this.idevento = idevento;
		this.nombre = nombre;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.descripcion = descripcion;
	}

	public Evento(int idevento, String nombre, Date fechaInicio, Date fechaFin, String horaInicio, String horaFin,
			String descripcion, Set<Poligono> poligonos, Set<Punto> puntos) {
		this.idevento = idevento;
		this.nombre = nombre;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.descripcion = descripcion;
		this.poligonos = poligonos;
		this.puntos = puntos;
	}

	
	/*@Column(name = "idevento", unique = true, nullable = false)*/
	public int getIdevento() {
		return this.idevento;
	}

	public void setIdevento(int idevento) {
		this.idevento = idevento;
	}

	@Column(name = "nombre", nullable = false, length = 65)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", nullable = false, length = 10)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", nullable = false, length = 10)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "hora_inicio", nullable = false, length = 5)
	public String getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(String horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Column(name = "hora_fin", nullable = false, length = 5)
	public String getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(String horaFin) {
		this.horaFin = horaFin;
	}

	@Column(name = "descripcion", nullable = false, length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evento")
	public Set<Poligono> getPoligonos() {
		return this.poligonos;
	}

	public void setPoligonos(Set<Poligono> poligonos) {
		this.poligonos = poligonos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evento")
	public Set<Punto> getPuntos() {
		return this.puntos;
	}

	public void setPuntos(Set<Punto> puntos) {
		this.puntos = puntos;
	}

}
