package entities;
// Generated 11/04/2020 11:08:44 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Poligono generated by hbm2java
 */
@Entity
@Table(name = "poligono", catalog = "localizapp")
public class Poligono implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	
	@OneToOne(fetch = FetchType.EAGER)
	private Evento evento;
	
	@OneToOne(fetch = FetchType.EAGER)
	private Usuario usuario;
	
	private String nombre;
	private byte[] polygon;
	private String descripcion;
	

	public Poligono() {
	}

	public Poligono(int idpoligono, Evento evento, Usuario usuario, String nombre, byte[] polygon, String descripcion) {
		this.id = idpoligono;
		this.usuario = usuario;
		this.evento = evento;
		this.nombre = nombre;
		this.polygon = polygon;
		this.descripcion = descripcion;
	}


	/*@Column(name = "idpoligono", unique = true, nullable = false)*/
	public int getIdpoligono() {
		return this.id;
	}

	public void setIdpoligono(int idpoligono) {
		this.id = idpoligono;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "evento_idevento", nullable = false)*/
	@Column(name = "id_evento", nullable = false)
	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "polygon", nullable = false)
	public byte[] getPolygon() {
		return this.polygon;
	}

	public void setPolygon(byte[] polygon) {
		this.polygon = polygon;
	}

	@Column(name = "descripcion", nullable = false, length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	
	@Column(name = "usuario", nullable = false, length = 200)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
