package entities;
// Generated 11/04/2020 11:08:44 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Punto generated by hbm2java
 */
@Entity
@Table(name = "punto", catalog = "localizapp")
public class Punto implements java.io.Serializable {

	private int idpunto;
	private Evento evento;
	private Usuario usuario;
	private String nombre;
	private byte[] coordenadas;
	private Set<Funcion> funcions = new HashSet<Funcion>(0);

	public Punto() {
	}

	public Punto(int idpunto, Evento evento, Usuario usuario, String nombre, byte[] coordenadas) {
		this.idpunto = idpunto;
		this.evento = evento;
		this.usuario = usuario;
		this.nombre = nombre;
		this.coordenadas = coordenadas;
	}

	public Punto(int idpunto, Evento evento, Usuario usuario, String nombre, byte[] coordenadas,
			Set<Funcion> funcions) {
		this.idpunto = idpunto;
		this.evento = evento;
		this.usuario = usuario;
		this.nombre = nombre;
		this.coordenadas = coordenadas;
		this.funcions = funcions;
	}

	@Id

	@Column(name = "idpunto", unique = true, nullable = false)
	public int getIdpunto() {
		return this.idpunto;
	}

	public void setIdpunto(int idpunto) {
		this.idpunto = idpunto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "evento_idevento", nullable = false)
	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "coordenadas", nullable = false)
	public byte[] getCoordenadas() {
		return this.coordenadas;
	}

	public void setCoordenadas(byte[] coordenadas) {
		this.coordenadas = coordenadas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "punto")
	public Set<Funcion> getFuncions() {
		return this.funcions;
	}

	public void setFuncions(Set<Funcion> funcions) {
		this.funcions = funcions;
	}

}
